/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceIndexRouteImport } from './routes/api-reference/index'
import { Route as ApiReferenceSplatRouteImport } from './routes/api-reference/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiReferenceWebhooksV1RouteImport } from './routes/api-reference/webhooks/v1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceIndexRoute = ApiReferenceIndexRouteImport.update({
  id: '/api-reference/',
  path: '/api-reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceSplatRoute = ApiReferenceSplatRouteImport.update({
  id: '/api-reference/$',
  path: '/api-reference/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceWebhooksV1Route = ApiReferenceWebhooksV1RouteImport.update({
  id: '/api-reference/webhooks/v1',
  path: '/api-reference/webhooks/v1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference/$': typeof ApiReferenceSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
  '/api-reference/webhooks/v1': typeof ApiReferenceWebhooksV1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-reference/$': typeof ApiReferenceSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/api-reference': typeof ApiReferenceIndexRoute
  '/api-reference/webhooks/v1': typeof ApiReferenceWebhooksV1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference/$': typeof ApiReferenceSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
  '/api-reference/webhooks/v1': typeof ApiReferenceWebhooksV1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference/$'
    | '/api/search'
    | '/docs/$'
    | '/api-reference/'
    | '/api-reference/webhooks/v1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-reference/$'
    | '/api/search'
    | '/docs/$'
    | '/api-reference'
    | '/api-reference/webhooks/v1'
  id:
    | '__root__'
    | '/'
    | '/api-reference/$'
    | '/api/search'
    | '/docs/$'
    | '/api-reference/'
    | '/api-reference/webhooks/v1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceSplatRoute: typeof ApiReferenceSplatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiReferenceIndexRoute: typeof ApiReferenceIndexRoute
  ApiReferenceWebhooksV1Route: typeof ApiReferenceWebhooksV1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/': {
      id: '/api-reference/'
      path: '/api-reference'
      fullPath: '/api-reference/'
      preLoaderRoute: typeof ApiReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/$': {
      id: '/api-reference/$'
      path: '/api-reference/$'
      fullPath: '/api-reference/$'
      preLoaderRoute: typeof ApiReferenceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/webhooks/v1': {
      id: '/api-reference/webhooks/v1'
      path: '/api-reference/webhooks/v1'
      fullPath: '/api-reference/webhooks/v1'
      preLoaderRoute: typeof ApiReferenceWebhooksV1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceSplatRoute: ApiReferenceSplatRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiReferenceIndexRoute: ApiReferenceIndexRoute,
  ApiReferenceWebhooksV1Route: ApiReferenceWebhooksV1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
