ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_revision_key_unique";--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_revision_position_unique";--> statement-breakpoint
ALTER TABLE "cms_collection_field" DROP CONSTRAINT "cms_field_api_key_valid";--> statement-breakpoint
ALTER TABLE "cms_collection_field" DROP CONSTRAINT "cms_field_display_label_valid";--> statement-breakpoint
ALTER TABLE "cms_collection_field" DROP CONSTRAINT "cms_field_kind_valid";--> statement-breakpoint
ALTER TABLE "cms_collection_field" DROP CONSTRAINT "cms_field_localization_valid";--> statement-breakpoint
ALTER TABLE "cms_collection_field" DROP CONSTRAINT "cms_field_configuration_valid";--> statement-breakpoint
ALTER TABLE "cms_collection_field" DROP CONSTRAINT "cms_field_lifecycle_consistent";--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_api_key_valid";--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_label_valid";--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_kind_valid";--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_localization_valid";--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_position_valid";--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" DROP CONSTRAINT "cms_revision_field_configuration_valid";--> statement-breakpoint
DROP INDEX "cms_field_collection_active_key_unique";--> statement-breakpoint
DROP INDEX "cms_field_collection_active_position_unique";--> statement-breakpoint
DROP INDEX "cms_field_collection_active_position_id_idx";--> statement-breakpoint
DROP INDEX "cms_revision_field_revision_position_idx";--> statement-breakpoint
ALTER TABLE "cms_collection_field" ALTER COLUMN "api_key" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ALTER COLUMN "display_label" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ALTER COLUMN "required" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ALTER COLUMN "localization" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ALTER COLUMN "api_key" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ALTER COLUMN "display_label" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ALTER COLUMN "required" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ALTER COLUMN "localization" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD COLUMN "parent_field_id" uuid;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD COLUMN "node_role" varchar(32) DEFAULT 'root' NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD COLUMN "reference_collection_id" uuid;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD COLUMN "editor_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_schema_head" ADD COLUMN "validation_profile" varchar(64) DEFAULT 'ffd-fields@1' NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_schema_head" ADD COLUMN "currency_registry_profile" varchar(64);--> statement-breakpoint
ALTER TABLE "cms_collection_schema_head" ADD COLUMN "editor_layout" jsonb;--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD COLUMN "format_version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD COLUMN "validation_profile" varchar(64) DEFAULT 'legacy-m5' NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD COLUMN "currency_registry_profile" varchar(64);--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD COLUMN "editor_layout" jsonb;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD COLUMN "parent_field_id" uuid;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD COLUMN "node_role" varchar(32) DEFAULT 'root' NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD COLUMN "reference_collection_id" uuid;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD COLUMN "editor_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_parent_tenant_fk" FOREIGN KEY ("parent_field_id","collection_id","environment_id","project_id","workspace_id") REFERENCES "public"."cms_collection_field"("id","collection_id","environment_id","project_id","workspace_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_reference_collection_tenant_fk" FOREIGN KEY ("reference_collection_id","environment_id","project_id","workspace_id") REFERENCES "public"."cms_collection"("id","environment_id","project_id","workspace_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_parent_fk" FOREIGN KEY ("revision_id","parent_field_id") REFERENCES "public"."cms_schema_revision_field"("revision_id","field_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_reference_collection_tenant_fk" FOREIGN KEY ("reference_collection_id","environment_id","project_id","workspace_id") REFERENCES "public"."cms_collection"("id","environment_id","project_id","workspace_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "cms_field_collection_active_root_key_unique" ON "cms_collection_field" USING btree ("collection_id","api_key") WHERE "cms_collection_field"."removed_at" is null and "cms_collection_field"."node_role" = 'root';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_field_collection_active_child_key_unique" ON "cms_collection_field" USING btree ("collection_id","parent_field_id","api_key") WHERE "cms_collection_field"."removed_at" is null and "cms_collection_field"."node_role" = 'object_property';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_field_collection_active_root_position_unique" ON "cms_collection_field" USING btree ("collection_id","position") WHERE "cms_collection_field"."removed_at" is null and "cms_collection_field"."node_role" = 'root';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_field_collection_active_child_position_unique" ON "cms_collection_field" USING btree ("collection_id","parent_field_id","position") WHERE "cms_collection_field"."removed_at" is null and "cms_collection_field"."node_role" = 'object_property';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_field_collection_active_list_item_unique" ON "cms_collection_field" USING btree ("collection_id","parent_field_id") WHERE "cms_collection_field"."removed_at" is null and "cms_collection_field"."node_role" = 'list_item';--> statement-breakpoint
CREATE INDEX "cms_field_collection_parent_position_id_idx" ON "cms_collection_field" USING btree ("collection_id","parent_field_id","position","id") WHERE "cms_collection_field"."removed_at" is null;--> statement-breakpoint
CREATE INDEX "cms_field_parent_idx" ON "cms_collection_field" USING btree ("parent_field_id") WHERE "cms_collection_field"."parent_field_id" is not null;--> statement-breakpoint
CREATE INDEX "cms_field_reference_collection_idx" ON "cms_collection_field" USING btree ("reference_collection_id") WHERE "cms_collection_field"."reference_collection_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "cms_revision_field_root_key_unique" ON "cms_schema_revision_field" USING btree ("revision_id","api_key") WHERE "cms_schema_revision_field"."node_role" = 'root';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_revision_field_child_key_unique" ON "cms_schema_revision_field" USING btree ("revision_id","parent_field_id","api_key") WHERE "cms_schema_revision_field"."node_role" = 'object_property';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_revision_field_root_position_unique" ON "cms_schema_revision_field" USING btree ("revision_id","position") WHERE "cms_schema_revision_field"."node_role" = 'root';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_revision_field_child_position_unique" ON "cms_schema_revision_field" USING btree ("revision_id","parent_field_id","position") WHERE "cms_schema_revision_field"."node_role" = 'object_property';--> statement-breakpoint
CREATE UNIQUE INDEX "cms_revision_field_list_item_unique" ON "cms_schema_revision_field" USING btree ("revision_id","parent_field_id") WHERE "cms_schema_revision_field"."node_role" = 'list_item';--> statement-breakpoint
CREATE INDEX "cms_revision_field_parent_position_idx" ON "cms_schema_revision_field" USING btree ("revision_id","parent_field_id","position","field_id");--> statement-breakpoint
CREATE INDEX "cms_revision_field_parent_idx" ON "cms_schema_revision_field" USING btree ("parent_field_id") WHERE "cms_schema_revision_field"."parent_field_id" is not null;--> statement-breakpoint
CREATE INDEX "cms_revision_field_reference_collection_idx" ON "cms_schema_revision_field" USING btree ("reference_collection_id") WHERE "cms_schema_revision_field"."reference_collection_id" is not null;--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_node_role_valid" CHECK ("cms_collection_field"."node_role" in ('root', 'object_property', 'list_item') and (("cms_collection_field"."node_role" = 'root' and "cms_collection_field"."parent_field_id" is null) or ("cms_collection_field"."node_role" <> 'root' and "cms_collection_field"."parent_field_id" is not null)));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_not_self_parented" CHECK ("cms_collection_field"."parent_field_id" is null or "cms_collection_field"."parent_field_id" <> "cms_collection_field"."id");--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_mixed_object_valid" CHECK ("cms_collection_field"."localization" is distinct from 'mixed' or ("cms_collection_field"."kind" = 'object' and "cms_collection_field"."required" is null and not ("cms_collection_field"."configuration" ? 'default')));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_required_valid" CHECK (("cms_collection_field"."node_role" = 'list_item' and "cms_collection_field"."required" is null) or ("cms_collection_field"."node_role" <> 'list_item' and (("cms_collection_field"."localization" = 'mixed' and "cms_collection_field"."required" is null) or ("cms_collection_field"."localization" is distinct from 'mixed' and "cms_collection_field"."required" is not null))));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_reference_target_valid" CHECK (("cms_collection_field"."kind" = 'reference' and "cms_collection_field"."reference_collection_id" is not null) or ("cms_collection_field"."kind" <> 'reference' and "cms_collection_field"."reference_collection_id" is null));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_editor_metadata_valid" CHECK (jsonb_typeof("cms_collection_field"."editor_metadata") = 'object' and octet_length("cms_collection_field"."editor_metadata"::text) <= 8192);--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_api_key_valid" CHECK (("cms_collection_field"."node_role" = 'list_item' and "cms_collection_field"."api_key" is null) or ("cms_collection_field"."node_role" <> 'list_item' and "cms_collection_field"."api_key" ~ '^[a-z][a-z0-9_]{0,62}$' and "cms_collection_field"."api_key" !~ '__' and right("cms_collection_field"."api_key", 1) <> '_'));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_display_label_valid" CHECK (("cms_collection_field"."node_role" = 'list_item' and "cms_collection_field"."display_label" is null) or ("cms_collection_field"."node_role" <> 'list_item' and char_length("cms_collection_field"."display_label") between 1 and 100 and "cms_collection_field"."display_label" = btrim("cms_collection_field"."display_label") and "cms_collection_field"."display_label" !~ '[[:cntrl:]]'));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_kind_valid" CHECK ("cms_collection_field"."kind" in ('short_text', 'long_text', 'rich_text', 'number', 'decimal', 'money', 'boolean', 'date', 'date_time', 'enum', 'url', 'email', 'slug', 'json', 'object', 'list', 'reference', 'external_asset'));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_localization_valid" CHECK (("cms_collection_field"."node_role" = 'root' and "cms_collection_field"."localization" in ('localized', 'shared', 'mixed')) or ("cms_collection_field"."node_role" = 'object_property' and ("cms_collection_field"."localization" is null or "cms_collection_field"."localization" in ('localized', 'shared', 'mixed'))) or ("cms_collection_field"."node_role" = 'list_item' and "cms_collection_field"."localization" is null));--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_configuration_valid" CHECK (jsonb_typeof("cms_collection_field"."configuration") = 'object' and octet_length("cms_collection_field"."configuration"::text) <= 327680);--> statement-breakpoint
ALTER TABLE "cms_collection_field" ADD CONSTRAINT "cms_field_lifecycle_consistent" CHECK (("cms_collection_field"."removed_at" is null and "cms_collection_field"."removed_by_user_id" is null and (("cms_collection_field"."node_role" = 'list_item' and "cms_collection_field"."position" = 0) or ("cms_collection_field"."node_role" <> 'list_item' and "cms_collection_field"."position" between 0 and 99))) or ("cms_collection_field"."removed_at" is not null and "cms_collection_field"."removed_by_user_id" is not null and "cms_collection_field"."position" is null));--> statement-breakpoint
ALTER TABLE "cms_collection_schema_head" ADD CONSTRAINT "cms_head_validation_profile_valid" CHECK ("cms_collection_schema_head"."validation_profile" ~ '^[a-z0-9][a-z0-9@._-]{0,63}$');--> statement-breakpoint
ALTER TABLE "cms_collection_schema_head" ADD CONSTRAINT "cms_head_currency_profile_valid" CHECK ("cms_collection_schema_head"."currency_registry_profile" is null or "cms_collection_schema_head"."currency_registry_profile" ~ '^iso-4217@[0-9]{4}-[0-9]{2}-[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "cms_collection_schema_head" ADD CONSTRAINT "cms_head_editor_layout_valid" CHECK ("cms_collection_schema_head"."editor_layout" is null or (jsonb_typeof("cms_collection_schema_head"."editor_layout") = 'object' and octet_length("cms_collection_schema_head"."editor_layout"::text) <= 32768));--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD CONSTRAINT "cms_revision_format_version_valid" CHECK ("cms_schema_revision"."format_version" in (1, 2));--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD CONSTRAINT "cms_revision_validation_profile_valid" CHECK ("cms_schema_revision"."validation_profile" ~ '^[a-z0-9][a-z0-9@._-]{0,63}$');--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD CONSTRAINT "cms_revision_currency_profile_valid" CHECK ("cms_schema_revision"."currency_registry_profile" is null or "cms_schema_revision"."currency_registry_profile" ~ '^iso-4217@[0-9]{4}-[0-9]{2}-[0-9]{2}$');--> statement-breakpoint
ALTER TABLE "cms_schema_revision" ADD CONSTRAINT "cms_revision_editor_layout_valid" CHECK ("cms_schema_revision"."editor_layout" is null or (jsonb_typeof("cms_schema_revision"."editor_layout") = 'object' and octet_length("cms_schema_revision"."editor_layout"::text) <= 32768));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_node_role_valid" CHECK ("cms_schema_revision_field"."node_role" in ('root', 'object_property', 'list_item') and (("cms_schema_revision_field"."node_role" = 'root' and "cms_schema_revision_field"."parent_field_id" is null) or ("cms_schema_revision_field"."node_role" <> 'root' and "cms_schema_revision_field"."parent_field_id" is not null)));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_not_self_parented" CHECK ("cms_schema_revision_field"."parent_field_id" is null or "cms_schema_revision_field"."parent_field_id" <> "cms_schema_revision_field"."field_id");--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_mixed_object_valid" CHECK ("cms_schema_revision_field"."localization" is distinct from 'mixed' or ("cms_schema_revision_field"."kind" = 'object' and "cms_schema_revision_field"."required" is null and not ("cms_schema_revision_field"."configuration" ? 'default')));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_required_valid" CHECK (("cms_schema_revision_field"."node_role" = 'list_item' and "cms_schema_revision_field"."required" is null) or ("cms_schema_revision_field"."node_role" <> 'list_item' and (("cms_schema_revision_field"."localization" = 'mixed' and "cms_schema_revision_field"."required" is null) or ("cms_schema_revision_field"."localization" is distinct from 'mixed' and "cms_schema_revision_field"."required" is not null))));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_reference_target_valid" CHECK (("cms_schema_revision_field"."kind" = 'reference' and "cms_schema_revision_field"."reference_collection_id" is not null) or ("cms_schema_revision_field"."kind" <> 'reference' and "cms_schema_revision_field"."reference_collection_id" is null));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_editor_metadata_valid" CHECK (jsonb_typeof("cms_schema_revision_field"."editor_metadata") = 'object' and octet_length("cms_schema_revision_field"."editor_metadata"::text) <= 8192);--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_api_key_valid" CHECK (("cms_schema_revision_field"."node_role" = 'list_item' and "cms_schema_revision_field"."api_key" is null) or ("cms_schema_revision_field"."node_role" <> 'list_item' and "cms_schema_revision_field"."api_key" ~ '^[a-z][a-z0-9_]{0,62}$' and "cms_schema_revision_field"."api_key" !~ '__' and right("cms_schema_revision_field"."api_key", 1) <> '_'));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_label_valid" CHECK (("cms_schema_revision_field"."node_role" = 'list_item' and "cms_schema_revision_field"."display_label" is null) or ("cms_schema_revision_field"."node_role" <> 'list_item' and char_length("cms_schema_revision_field"."display_label") between 1 and 100 and "cms_schema_revision_field"."display_label" = btrim("cms_schema_revision_field"."display_label") and "cms_schema_revision_field"."display_label" !~ '[[:cntrl:]]'));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_kind_valid" CHECK ("cms_schema_revision_field"."kind" in ('short_text', 'long_text', 'rich_text', 'number', 'decimal', 'money', 'boolean', 'date', 'date_time', 'enum', 'url', 'email', 'slug', 'json', 'object', 'list', 'reference', 'external_asset'));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_localization_valid" CHECK (("cms_schema_revision_field"."node_role" = 'root' and "cms_schema_revision_field"."localization" in ('localized', 'shared', 'mixed')) or ("cms_schema_revision_field"."node_role" = 'object_property' and ("cms_schema_revision_field"."localization" is null or "cms_schema_revision_field"."localization" in ('localized', 'shared', 'mixed'))) or ("cms_schema_revision_field"."node_role" = 'list_item' and "cms_schema_revision_field"."localization" is null));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_position_valid" CHECK (("cms_schema_revision_field"."node_role" = 'list_item' and "cms_schema_revision_field"."position" = 0) or ("cms_schema_revision_field"."node_role" <> 'list_item' and "cms_schema_revision_field"."position" between 0 and 99));--> statement-breakpoint
ALTER TABLE "cms_schema_revision_field" ADD CONSTRAINT "cms_revision_field_configuration_valid" CHECK (jsonb_typeof("cms_schema_revision_field"."configuration") = 'object' and octet_length("cms_schema_revision_field"."configuration"::text) <= 327680);