CREATE TABLE "project_invitation_locale_access" (
	"invitation_id" uuid NOT NULL,
	"workspace_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"locale_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "project_invitation_locale_access_invitation_locale_pk" PRIMARY KEY("invitation_id","locale_id")
);
--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" DROP CONSTRAINT "control_plane_command_receipt_operation_valid";--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" DROP CONSTRAINT "control_plane_command_receipt_result_type_valid";--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" DROP CONSTRAINT "control_plane_command_receipt_scope_result_valid";--> statement-breakpoint
DROP INDEX "project_locale_created_by_user_idx";--> statement-breakpoint
DROP INDEX "project_locale_changed_by_user_idx";--> statement-breakpoint
ALTER TABLE "project_locale" ALTER COLUMN "created_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "project_locale" ALTER COLUMN "changed_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "project_invitation" ADD COLUMN "locale_access_mode" varchar(16) DEFAULT 'all' NOT NULL;--> statement-breakpoint
ALTER TABLE "project_locale" ADD COLUMN "created_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "project_locale" ADD COLUMN "created_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "project_locale" ADD COLUMN "changed_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "project_locale" ADD COLUMN "changed_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "project_invitation" ADD CONSTRAINT "project_invitation_id_project_workspace_unique" UNIQUE("id","project_id","workspace_id");--> statement-breakpoint
ALTER TABLE "project_invitation_locale_access" ADD CONSTRAINT "project_invitation_locale_access_invitation_tenant_fk" FOREIGN KEY ("invitation_id","project_id","workspace_id") REFERENCES "public"."project_invitation"("id","project_id","workspace_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_invitation_locale_access" ADD CONSTRAINT "project_invitation_locale_access_locale_tenant_fk" FOREIGN KEY ("locale_id","project_id","workspace_id") REFERENCES "public"."project_locale"("id","project_id","workspace_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "project_invitation_locale_access_locale_idx" ON "project_invitation_locale_access" USING btree ("locale_id");--> statement-breakpoint
ALTER TABLE "project_locale" ADD CONSTRAINT "project_locale_created_credential_tenant_fk" FOREIGN KEY ("created_by_credential_id","workspace_id","project_id","created_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_locale" ADD CONSTRAINT "project_locale_changed_credential_tenant_fk" FOREIGN KEY ("changed_by_credential_id","workspace_id","project_id","changed_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "project_locale_created_by_credential_idx" ON "project_locale" USING btree ("created_by_credential_id","created_by_credential_environment_id") WHERE "project_locale"."created_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "project_locale_changed_by_credential_idx" ON "project_locale" USING btree ("changed_by_credential_id","changed_by_credential_environment_id") WHERE "project_locale"."changed_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "project_locale_created_by_user_idx" ON "project_locale" USING btree ("created_by_user_id") WHERE "project_locale"."created_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "project_locale_changed_by_user_idx" ON "project_locale" USING btree ("changed_by_user_id") WHERE "project_locale"."changed_by_user_id" is not null;--> statement-breakpoint
ALTER TABLE "project_invitation" ADD CONSTRAINT "project_invitation_locale_access_mode_valid" CHECK ("project_invitation"."locale_access_mode" in ('all', 'selected', 'none'));--> statement-breakpoint
ALTER TABLE "project_invitation" ADD CONSTRAINT "project_invitation_owner_locale_access_all" CHECK ("project_invitation"."role" <> 'owner' or "project_invitation"."locale_access_mode" = 'all');--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" ADD CONSTRAINT "control_plane_command_receipt_operation_valid" CHECK ("control_plane_command_receipt"."operation" in ('workspace.create', 'project.create', 'project.capability.enable', 'studio_registration.put', 'project_locale.create'));--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" ADD CONSTRAINT "control_plane_command_receipt_result_type_valid" CHECK ("control_plane_command_receipt"."result_resource_type" in ('workspace', 'project', 'project_capability', 'studio_registration', 'project_locale'));--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" ADD CONSTRAINT "control_plane_command_receipt_scope_result_valid" CHECK (("control_plane_command_receipt"."operation" = 'workspace.create' and "control_plane_command_receipt"."actor_type" = 'user' and "control_plane_command_receipt"."project_id" is null and "control_plane_command_receipt"."environment_id" is null and "control_plane_command_receipt"."result_resource_type" = 'workspace' and "control_plane_command_receipt"."result_resource_id" = "control_plane_command_receipt"."workspace_id" and "control_plane_command_receipt"."result_disposition" = 'created') or ("control_plane_command_receipt"."operation" = 'project.create' and "control_plane_command_receipt"."actor_type" = 'user' and "control_plane_command_receipt"."project_id" is not null and "control_plane_command_receipt"."environment_id" is null and "control_plane_command_receipt"."result_resource_type" = 'project' and "control_plane_command_receipt"."result_resource_id" = "control_plane_command_receipt"."project_id" and "control_plane_command_receipt"."result_disposition" = 'created') or ("control_plane_command_receipt"."operation" = 'project.capability.enable' and "control_plane_command_receipt"."project_id" is not null and "control_plane_command_receipt"."environment_id" is not null and "control_plane_command_receipt"."result_resource_type" = 'project_capability' and "control_plane_command_receipt"."result_disposition" = 'created') or ("control_plane_command_receipt"."operation" = 'studio_registration.put' and "control_plane_command_receipt"."project_id" is not null and "control_plane_command_receipt"."environment_id" is not null and "control_plane_command_receipt"."result_resource_type" = 'studio_registration') or ("control_plane_command_receipt"."operation" = 'project_locale.create' and "control_plane_command_receipt"."project_id" is not null and (("control_plane_command_receipt"."actor_type" = 'user' and "control_plane_command_receipt"."environment_id" is null) or ("control_plane_command_receipt"."actor_type" = 'credential' and "control_plane_command_receipt"."environment_id" is not null)) and "control_plane_command_receipt"."result_resource_type" = 'project_locale' and "control_plane_command_receipt"."result_disposition" = 'created'));--> statement-breakpoint
ALTER TABLE "project_locale" ADD CONSTRAINT "project_locale_created_actor_exactly_one" CHECK (("project_locale"."created_by_user_id" is not null and "project_locale"."created_by_credential_id" is null and "project_locale"."created_by_credential_environment_id" is null) or ("project_locale"."created_by_user_id" is null and "project_locale"."created_by_credential_id" is not null and "project_locale"."created_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "project_locale" ADD CONSTRAINT "project_locale_changed_actor_exactly_one" CHECK (("project_locale"."changed_by_user_id" is not null and "project_locale"."changed_by_credential_id" is null and "project_locale"."changed_by_credential_environment_id" is null) or ("project_locale"."changed_by_user_id" is null and "project_locale"."changed_by_credential_id" is not null and "project_locale"."changed_by_credential_environment_id" is not null));