CREATE TABLE "api_credential_rotation" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workspace_id" uuid NOT NULL,
	"project_id" uuid NOT NULL,
	"environment_id" uuid NOT NULL,
	"predecessor_credential_id" uuid NOT NULL,
	"successor_credential_id" uuid NOT NULL,
	"status" varchar(16) DEFAULT 'pending' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by_user_id" text NOT NULL,
	"changed_by_user_id" text NOT NULL,
	"activated_at" timestamp with time zone,
	"retire_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"canceled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "api_credential_rotation_id_tenant_unique" UNIQUE("id","workspace_id","project_id","environment_id"),
	CONSTRAINT "api_credential_rotation_successor_unique" UNIQUE("successor_credential_id"),
	CONSTRAINT "api_credential_rotation_credentials_distinct" CHECK ("api_credential_rotation"."predecessor_credential_id" <> "api_credential_rotation"."successor_credential_id"),
	CONSTRAINT "api_credential_rotation_status_valid" CHECK ("api_credential_rotation"."status" in ('pending', 'overlap', 'canceled', 'completed')),
	CONSTRAINT "api_credential_rotation_version_positive" CHECK ("api_credential_rotation"."version" > 0),
	CONSTRAINT "api_credential_rotation_lifecycle_valid" CHECK (("api_credential_rotation"."status" = 'pending' and "api_credential_rotation"."activated_at" is null and "api_credential_rotation"."retire_at" is null and "api_credential_rotation"."completed_at" is null and "api_credential_rotation"."canceled_at" is null) or ("api_credential_rotation"."status" = 'overlap' and "api_credential_rotation"."activated_at" is not null and "api_credential_rotation"."retire_at" is not null and "api_credential_rotation"."retire_at" > "api_credential_rotation"."activated_at" and "api_credential_rotation"."completed_at" is null and "api_credential_rotation"."canceled_at" is null) or ("api_credential_rotation"."status" = 'canceled' and "api_credential_rotation"."activated_at" is null and "api_credential_rotation"."retire_at" is null and "api_credential_rotation"."completed_at" is null and "api_credential_rotation"."canceled_at" is not null) or ("api_credential_rotation"."status" = 'completed' and "api_credential_rotation"."activated_at" is not null and "api_credential_rotation"."retire_at" is not null and "api_credential_rotation"."completed_at" is not null and "api_credential_rotation"."completed_at" >= "api_credential_rotation"."activated_at" and "api_credential_rotation"."canceled_at" is null)),
	CONSTRAINT "api_credential_rotation_timestamps_valid" CHECK ("api_credential_rotation"."updated_at" >= "api_credential_rotation"."created_at")
);
--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" DROP CONSTRAINT "control_plane_command_receipt_operation_valid";--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" DROP CONSTRAINT "control_plane_command_receipt_result_type_valid";--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" DROP CONSTRAINT "control_plane_command_receipt_scope_result_valid";--> statement-breakpoint
ALTER TABLE "webhook_delivery" DROP CONSTRAINT "webhook_delivery_replay_authority_valid";--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" DROP CONSTRAINT "webhook_subscription_lifecycle_valid";--> statement-breakpoint
DROP INDEX "api_credential_rotated_from_unique";--> statement-breakpoint
DROP INDEX "cms_invalidation_mapping_created_by_idx";--> statement-breakpoint
DROP INDEX "cms_invalidation_mapping_changed_by_idx";--> statement-breakpoint
DROP INDEX "webhook_endpoint_created_by_idx";--> statement-breakpoint
DROP INDEX "webhook_endpoint_changed_by_idx";--> statement-breakpoint
DROP INDEX "webhook_destination_created_by_idx";--> statement-breakpoint
DROP INDEX "webhook_secret_created_by_idx";--> statement-breakpoint
DROP INDEX "webhook_secret_changed_by_idx";--> statement-breakpoint
DROP INDEX "webhook_subscription_created_by_idx";--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ALTER COLUMN "created_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ALTER COLUMN "changed_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ALTER COLUMN "created_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ALTER COLUMN "changed_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_destination" ALTER COLUMN "created_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ALTER COLUMN "created_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ALTER COLUMN "changed_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ALTER COLUMN "created_by_user_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "api_credential" ADD COLUMN "status" varchar(16) DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE "api_credential" ADD COLUMN "activated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "api_credential" ADD COLUMN "retire_at" timestamp with time zone;--> statement-breakpoint
UPDATE "api_credential"
SET
	"status" = CASE WHEN "revoked_at" IS NULL THEN 'active' ELSE 'revoked' END,
	"activated_at" = "created_at";--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD COLUMN "created_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD COLUMN "created_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD COLUMN "changed_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD COLUMN "changed_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_delivery" ADD COLUMN "replayed_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_delivery" ADD COLUMN "replayed_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD COLUMN "created_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD COLUMN "created_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD COLUMN "changed_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD COLUMN "changed_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_destination" ADD COLUMN "created_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_destination" ADD COLUMN "created_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD COLUMN "created_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD COLUMN "created_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD COLUMN "changed_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD COLUMN "changed_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD COLUMN "created_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD COLUMN "created_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD COLUMN "closed_by_credential_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD COLUMN "closed_by_credential_environment_id" uuid;--> statement-breakpoint
ALTER TABLE "api_credential_rotation" ADD CONSTRAINT "api_credential_rotation_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "api_credential_rotation" ADD CONSTRAINT "api_credential_rotation_changed_by_user_id_user_id_fk" FOREIGN KEY ("changed_by_user_id") REFERENCES "public"."user"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "api_credential_rotation" ADD CONSTRAINT "api_credential_rotation_predecessor_tenant_fk" FOREIGN KEY ("predecessor_credential_id","workspace_id","project_id","environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "api_credential_rotation" ADD CONSTRAINT "api_credential_rotation_successor_tenant_fk" FOREIGN KEY ("successor_credential_id","workspace_id","project_id","environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "api_credential_rotation_predecessor_open_unique" ON "api_credential_rotation" USING btree ("predecessor_credential_id") WHERE "api_credential_rotation"."status" in ('pending', 'overlap');--> statement-breakpoint
CREATE INDEX "api_credential_rotation_environment_status_created_id_idx" ON "api_credential_rotation" USING btree ("environment_id","status","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "api_credential_rotation_retiring_due_idx" ON "api_credential_rotation" USING btree ("retire_at","id") WHERE "api_credential_rotation"."status" = 'overlap';--> statement-breakpoint
CREATE INDEX "api_credential_rotation_created_by_user_idx" ON "api_credential_rotation" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "api_credential_rotation_changed_by_user_idx" ON "api_credential_rotation" USING btree ("changed_by_user_id");--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD CONSTRAINT "cms_invalidation_mapping_created_credential_tenant_fk" FOREIGN KEY ("created_by_credential_id","workspace_id","project_id","created_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD CONSTRAINT "cms_invalidation_mapping_changed_credential_tenant_fk" FOREIGN KEY ("changed_by_credential_id","workspace_id","project_id","changed_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_delivery" ADD CONSTRAINT "webhook_delivery_replayed_credential_tenant_fk" FOREIGN KEY ("replayed_by_credential_id","workspace_id","project_id","replayed_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD CONSTRAINT "webhook_endpoint_created_credential_tenant_fk" FOREIGN KEY ("created_by_credential_id","workspace_id","project_id","created_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD CONSTRAINT "webhook_endpoint_changed_credential_tenant_fk" FOREIGN KEY ("changed_by_credential_id","workspace_id","project_id","changed_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_destination" ADD CONSTRAINT "webhook_destination_created_credential_tenant_fk" FOREIGN KEY ("created_by_credential_id","workspace_id","project_id","created_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD CONSTRAINT "webhook_secret_created_credential_tenant_fk" FOREIGN KEY ("created_by_credential_id","workspace_id","project_id","created_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD CONSTRAINT "webhook_secret_changed_credential_tenant_fk" FOREIGN KEY ("changed_by_credential_id","workspace_id","project_id","changed_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD CONSTRAINT "webhook_subscription_created_credential_tenant_fk" FOREIGN KEY ("created_by_credential_id","workspace_id","project_id","created_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD CONSTRAINT "webhook_subscription_closed_credential_tenant_fk" FOREIGN KEY ("closed_by_credential_id","workspace_id","project_id","closed_by_credential_environment_id") REFERENCES "public"."api_credential"("id","workspace_id","project_id","environment_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "api_credential_rotation_lineage_idx" ON "api_credential" USING btree ("rotated_from_credential_id","created_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "api_credential"."rotated_from_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "api_credential_environment_status_created_id_idx" ON "api_credential" USING btree ("environment_id","status","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "api_credential_retiring_due_idx" ON "api_credential" USING btree ("retire_at","id") WHERE "api_credential"."status" = 'retiring';--> statement-breakpoint
CREATE INDEX "audit_event_project_environment_occurred_id_idx" ON "audit_event" USING btree ("project_id","environment_id","occurred_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "audit_event"."project_id" is not null and "audit_event"."environment_id" is not null;--> statement-breakpoint
CREATE INDEX "audit_event_project_actor_occurred_id_idx" ON "audit_event" USING btree ("project_id","actor_type","actor_id","occurred_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "audit_event"."project_id" is not null;--> statement-breakpoint
CREATE INDEX "audit_event_project_action_occurred_id_idx" ON "audit_event" USING btree ("project_id","action","occurred_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "audit_event"."project_id" is not null;--> statement-breakpoint
CREATE INDEX "cms_invalidation_mapping_created_by_credential_idx" ON "cms_invalidation_route_mapping" USING btree ("created_by_credential_id","created_by_credential_environment_id") WHERE "cms_invalidation_route_mapping"."created_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "cms_invalidation_mapping_changed_by_credential_idx" ON "cms_invalidation_route_mapping" USING btree ("changed_by_credential_id","changed_by_credential_environment_id") WHERE "cms_invalidation_route_mapping"."changed_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_delivery_replayed_by_credential_idx" ON "webhook_delivery" USING btree ("replayed_by_credential_id","replayed_by_credential_environment_id") WHERE "webhook_delivery"."replayed_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_endpoint_created_by_credential_idx" ON "webhook_endpoint" USING btree ("created_by_credential_id","created_by_credential_environment_id") WHERE "webhook_endpoint"."created_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_endpoint_changed_by_credential_idx" ON "webhook_endpoint" USING btree ("changed_by_credential_id","changed_by_credential_environment_id") WHERE "webhook_endpoint"."changed_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_destination_created_by_credential_idx" ON "webhook_endpoint_destination" USING btree ("created_by_credential_id","created_by_credential_environment_id") WHERE "webhook_endpoint_destination"."created_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_secret_created_by_credential_idx" ON "webhook_endpoint_secret" USING btree ("created_by_credential_id","created_by_credential_environment_id") WHERE "webhook_endpoint_secret"."created_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_secret_changed_by_credential_idx" ON "webhook_endpoint_secret" USING btree ("changed_by_credential_id","changed_by_credential_environment_id") WHERE "webhook_endpoint_secret"."changed_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_subscription_created_by_credential_idx" ON "webhook_endpoint_subscription" USING btree ("created_by_credential_id","created_by_credential_environment_id") WHERE "webhook_endpoint_subscription"."created_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_subscription_closed_by_credential_idx" ON "webhook_endpoint_subscription" USING btree ("closed_by_credential_id","closed_by_credential_environment_id") WHERE "webhook_endpoint_subscription"."closed_by_credential_id" is not null;--> statement-breakpoint
CREATE INDEX "cms_invalidation_mapping_created_by_idx" ON "cms_invalidation_route_mapping" USING btree ("created_by_user_id") WHERE "cms_invalidation_route_mapping"."created_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "cms_invalidation_mapping_changed_by_idx" ON "cms_invalidation_route_mapping" USING btree ("changed_by_user_id") WHERE "cms_invalidation_route_mapping"."changed_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_endpoint_created_by_idx" ON "webhook_endpoint" USING btree ("created_by_user_id") WHERE "webhook_endpoint"."created_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_endpoint_changed_by_idx" ON "webhook_endpoint" USING btree ("changed_by_user_id") WHERE "webhook_endpoint"."changed_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_destination_created_by_idx" ON "webhook_endpoint_destination" USING btree ("created_by_user_id") WHERE "webhook_endpoint_destination"."created_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_secret_created_by_idx" ON "webhook_endpoint_secret" USING btree ("created_by_user_id") WHERE "webhook_endpoint_secret"."created_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_secret_changed_by_idx" ON "webhook_endpoint_secret" USING btree ("changed_by_user_id") WHERE "webhook_endpoint_secret"."changed_by_user_id" is not null;--> statement-breakpoint
CREATE INDEX "webhook_subscription_created_by_idx" ON "webhook_endpoint_subscription" USING btree ("created_by_user_id") WHERE "webhook_endpoint_subscription"."created_by_user_id" is not null;--> statement-breakpoint
ALTER TABLE "api_credential" ADD CONSTRAINT "api_credential_status_valid" CHECK ("api_credential"."status" in ('pending', 'active', 'retiring', 'revoked', 'canceled'));--> statement-breakpoint
ALTER TABLE "api_credential" ADD CONSTRAINT "api_credential_lifecycle_valid" CHECK (("api_credential"."status" = 'pending' and "api_credential"."activated_at" is null and "api_credential"."retire_at" is null and "api_credential"."revoked_at" is null) or ("api_credential"."status" = 'active' and "api_credential"."activated_at" is not null and "api_credential"."retire_at" is null and "api_credential"."revoked_at" is null) or ("api_credential"."status" = 'retiring' and "api_credential"."activated_at" is not null and "api_credential"."retire_at" is not null and "api_credential"."retire_at" > "api_credential"."activated_at" and "api_credential"."revoked_at" is null) or ("api_credential"."status" = 'revoked' and "api_credential"."revoked_at" is not null) or ("api_credential"."status" = 'canceled' and "api_credential"."activated_at" is null and "api_credential"."retire_at" is null and "api_credential"."revoked_at" is not null));--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" ADD CONSTRAINT "control_plane_command_receipt_operation_valid" CHECK ("control_plane_command_receipt"."operation" in ('workspace.create', 'project.create', 'project.capability.enable', 'studio_registration.put', 'project_locale.create', 'invalidation_mapping.create'));--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" ADD CONSTRAINT "control_plane_command_receipt_result_type_valid" CHECK ("control_plane_command_receipt"."result_resource_type" in ('workspace', 'project', 'project_capability', 'studio_registration', 'project_locale', 'cms_invalidation_route_mapping'));--> statement-breakpoint
ALTER TABLE "control_plane_command_receipt" ADD CONSTRAINT "control_plane_command_receipt_scope_result_valid" CHECK (("control_plane_command_receipt"."operation" = 'workspace.create' and "control_plane_command_receipt"."actor_type" = 'user' and "control_plane_command_receipt"."project_id" is null and "control_plane_command_receipt"."environment_id" is null and "control_plane_command_receipt"."result_resource_type" = 'workspace' and "control_plane_command_receipt"."result_resource_id" = "control_plane_command_receipt"."workspace_id" and "control_plane_command_receipt"."result_disposition" = 'created') or ("control_plane_command_receipt"."operation" = 'project.create' and "control_plane_command_receipt"."actor_type" = 'user' and "control_plane_command_receipt"."project_id" is not null and "control_plane_command_receipt"."environment_id" is null and "control_plane_command_receipt"."result_resource_type" = 'project' and "control_plane_command_receipt"."result_resource_id" = "control_plane_command_receipt"."project_id" and "control_plane_command_receipt"."result_disposition" = 'created') or ("control_plane_command_receipt"."operation" = 'project.capability.enable' and "control_plane_command_receipt"."project_id" is not null and "control_plane_command_receipt"."environment_id" is not null and "control_plane_command_receipt"."result_resource_type" = 'project_capability' and "control_plane_command_receipt"."result_disposition" = 'created') or ("control_plane_command_receipt"."operation" = 'studio_registration.put' and "control_plane_command_receipt"."project_id" is not null and "control_plane_command_receipt"."environment_id" is not null and "control_plane_command_receipt"."result_resource_type" = 'studio_registration') or ("control_plane_command_receipt"."operation" = 'project_locale.create' and "control_plane_command_receipt"."project_id" is not null and (("control_plane_command_receipt"."actor_type" = 'user' and "control_plane_command_receipt"."environment_id" is null) or ("control_plane_command_receipt"."actor_type" = 'credential' and "control_plane_command_receipt"."environment_id" is not null)) and "control_plane_command_receipt"."result_resource_type" = 'project_locale' and "control_plane_command_receipt"."result_disposition" = 'created') or ("control_plane_command_receipt"."operation" = 'invalidation_mapping.create' and "control_plane_command_receipt"."project_id" is not null and "control_plane_command_receipt"."environment_id" is not null and "control_plane_command_receipt"."result_resource_type" = 'cms_invalidation_route_mapping' and "control_plane_command_receipt"."result_disposition" = 'created'));--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD CONSTRAINT "cms_invalidation_mapping_created_actor_exactly_one" CHECK (("cms_invalidation_route_mapping"."created_by_user_id" is not null and "cms_invalidation_route_mapping"."created_by_credential_id" is null and "cms_invalidation_route_mapping"."created_by_credential_environment_id" is null) or ("cms_invalidation_route_mapping"."created_by_user_id" is null and "cms_invalidation_route_mapping"."created_by_credential_id" is not null and "cms_invalidation_route_mapping"."created_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "cms_invalidation_route_mapping" ADD CONSTRAINT "cms_invalidation_mapping_changed_actor_exactly_one" CHECK (("cms_invalidation_route_mapping"."changed_by_user_id" is not null and "cms_invalidation_route_mapping"."changed_by_credential_id" is null and "cms_invalidation_route_mapping"."changed_by_credential_environment_id" is null) or ("cms_invalidation_route_mapping"."changed_by_user_id" is null and "cms_invalidation_route_mapping"."changed_by_credential_id" is not null and "cms_invalidation_route_mapping"."changed_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "webhook_delivery" ADD CONSTRAINT "webhook_delivery_replay_authority_valid" CHECK (("webhook_delivery"."kind" = 'initial' and "webhook_delivery"."source_delivery_id" is null and "webhook_delivery"."replay_command_id" is null and "webhook_delivery"."replay_command_fingerprint" is null and "webhook_delivery"."replayed_by_user_id" is null and "webhook_delivery"."replayed_by_credential_id" is null and "webhook_delivery"."replayed_by_credential_environment_id" is null) or ("webhook_delivery"."kind" = 'replay' and "webhook_delivery"."replay_command_id" is not null and "webhook_delivery"."replay_command_fingerprint" ~ '^[0-9a-f]{64}$' and (("webhook_delivery"."replayed_by_user_id" is not null and "webhook_delivery"."replayed_by_credential_id" is null and "webhook_delivery"."replayed_by_credential_environment_id" is null) or ("webhook_delivery"."replayed_by_user_id" is null and "webhook_delivery"."replayed_by_credential_id" is not null and "webhook_delivery"."replayed_by_credential_environment_id" is not null))));--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD CONSTRAINT "webhook_endpoint_created_actor_exactly_one" CHECK (("webhook_endpoint"."created_by_user_id" is not null and "webhook_endpoint"."created_by_credential_id" is null and "webhook_endpoint"."created_by_credential_environment_id" is null) or ("webhook_endpoint"."created_by_user_id" is null and "webhook_endpoint"."created_by_credential_id" is not null and "webhook_endpoint"."created_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "webhook_endpoint" ADD CONSTRAINT "webhook_endpoint_changed_actor_exactly_one" CHECK (("webhook_endpoint"."changed_by_user_id" is not null and "webhook_endpoint"."changed_by_credential_id" is null and "webhook_endpoint"."changed_by_credential_environment_id" is null) or ("webhook_endpoint"."changed_by_user_id" is null and "webhook_endpoint"."changed_by_credential_id" is not null and "webhook_endpoint"."changed_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "webhook_endpoint_destination" ADD CONSTRAINT "webhook_destination_created_actor_exactly_one" CHECK (("webhook_endpoint_destination"."created_by_user_id" is not null and "webhook_endpoint_destination"."created_by_credential_id" is null and "webhook_endpoint_destination"."created_by_credential_environment_id" is null) or ("webhook_endpoint_destination"."created_by_user_id" is null and "webhook_endpoint_destination"."created_by_credential_id" is not null and "webhook_endpoint_destination"."created_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD CONSTRAINT "webhook_secret_created_actor_exactly_one" CHECK (("webhook_endpoint_secret"."created_by_user_id" is not null and "webhook_endpoint_secret"."created_by_credential_id" is null and "webhook_endpoint_secret"."created_by_credential_environment_id" is null) or ("webhook_endpoint_secret"."created_by_user_id" is null and "webhook_endpoint_secret"."created_by_credential_id" is not null and "webhook_endpoint_secret"."created_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "webhook_endpoint_secret" ADD CONSTRAINT "webhook_secret_changed_actor_exactly_one" CHECK (("webhook_endpoint_secret"."changed_by_user_id" is not null and "webhook_endpoint_secret"."changed_by_credential_id" is null and "webhook_endpoint_secret"."changed_by_credential_environment_id" is null) or ("webhook_endpoint_secret"."changed_by_user_id" is null and "webhook_endpoint_secret"."changed_by_credential_id" is not null and "webhook_endpoint_secret"."changed_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD CONSTRAINT "webhook_subscription_created_actor_exactly_one" CHECK (("webhook_endpoint_subscription"."created_by_user_id" is not null and "webhook_endpoint_subscription"."created_by_credential_id" is null and "webhook_endpoint_subscription"."created_by_credential_environment_id" is null) or ("webhook_endpoint_subscription"."created_by_user_id" is null and "webhook_endpoint_subscription"."created_by_credential_id" is not null and "webhook_endpoint_subscription"."created_by_credential_environment_id" is not null));--> statement-breakpoint
ALTER TABLE "webhook_endpoint_subscription" ADD CONSTRAINT "webhook_subscription_lifecycle_valid" CHECK (("webhook_endpoint_subscription"."active_until" is null and "webhook_endpoint_subscription"."closed_by_user_id" is null and "webhook_endpoint_subscription"."closed_by_credential_id" is null and "webhook_endpoint_subscription"."closed_by_credential_environment_id" is null) or ("webhook_endpoint_subscription"."active_until" is not null and "webhook_endpoint_subscription"."active_until" >= "webhook_endpoint_subscription"."active_from" and (("webhook_endpoint_subscription"."closed_by_user_id" is not null and "webhook_endpoint_subscription"."closed_by_credential_id" is null and "webhook_endpoint_subscription"."closed_by_credential_environment_id" is null) or ("webhook_endpoint_subscription"."closed_by_user_id" is null and "webhook_endpoint_subscription"."closed_by_credential_id" is not null and "webhook_endpoint_subscription"."closed_by_credential_environment_id" is not null))));