/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthProjectsProjectIdRouteImport } from './routes/_auth/projects/$projectId'
import { Route as AuthProjectsProjectIdOperationsRouteImport } from './routes/_auth/projects/$projectId_/operations'
import { Route as AuthProjectsProjectIdWebhooksRouteImport } from './routes/_auth/projects/$projectId_/webhooks'
import { Route as AuthProjectsProjectIdCollectionsCollectionIdRouteImport } from './routes/_auth/projects/$projectId_/collections/$collectionId'
import { Route as AuthProjectsProjectIdCollectionsCollectionIdEntriesRouteImport } from './routes/_auth/projects/$projectId_/collections/$collectionId_/entries'
import { Route as AuthProjectsProjectIdCollectionsCollectionIdPresentationRouteImport } from './routes/_auth/projects/$projectId_/collections/$collectionId_/presentation'
import { Route as AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRouteImport } from './routes/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId'
import { Route as AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRouteImport } from './routes/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId_/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProjectsProjectIdOperationsRoute =
  AuthProjectsProjectIdOperationsRouteImport.update({
    id: '/projects/$projectId_/operations',
    path: '/projects/$projectId/operations',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthProjectsProjectIdWebhooksRoute =
  AuthProjectsProjectIdWebhooksRouteImport.update({
    id: '/projects/$projectId_/webhooks',
    path: '/projects/$projectId/webhooks',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthProjectsProjectIdCollectionsCollectionIdRoute =
  AuthProjectsProjectIdCollectionsCollectionIdRouteImport.update({
    id: '/projects/$projectId_/collections/$collectionId',
    path: '/projects/$projectId/collections/$collectionId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute =
  AuthProjectsProjectIdCollectionsCollectionIdEntriesRouteImport.update({
    id: '/projects/$projectId_/collections/$collectionId_/entries',
    path: '/projects/$projectId/collections/$collectionId/entries',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute =
  AuthProjectsProjectIdCollectionsCollectionIdPresentationRouteImport.update({
    id: '/projects/$projectId_/collections/$collectionId_/presentation',
    path: '/projects/$projectId/collections/$collectionId/presentation',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute =
  AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRouteImport.update({
    id: '/projects/$projectId_/collections/$collectionId_/entries_/$entryId',
    path: '/projects/$projectId/collections/$collectionId/entries/$entryId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute =
  AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRouteImport.update(
    {
      id: '/projects/$projectId_/collections/$collectionId_/entries_/$entryId_/preview',
      path: '/projects/$projectId/collections/$collectionId/entries/$entryId/preview',
      getParentRoute: () => AuthRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/projects/$projectId/operations': typeof AuthProjectsProjectIdOperationsRoute
  '/projects/$projectId/webhooks': typeof AuthProjectsProjectIdWebhooksRoute
  '/projects/$projectId/collections/$collectionId': typeof AuthProjectsProjectIdCollectionsCollectionIdRoute
  '/projects/$projectId/collections/$collectionId/entries': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute
  '/projects/$projectId/collections/$collectionId/presentation': typeof AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute
  '/projects/$projectId/collections/$collectionId/entries/$entryId': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute
  '/projects/$projectId/collections/$collectionId/entries/$entryId/preview': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/projects/$projectId/operations': typeof AuthProjectsProjectIdOperationsRoute
  '/projects/$projectId/webhooks': typeof AuthProjectsProjectIdWebhooksRoute
  '/projects/$projectId/collections/$collectionId': typeof AuthProjectsProjectIdCollectionsCollectionIdRoute
  '/projects/$projectId/collections/$collectionId/entries': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute
  '/projects/$projectId/collections/$collectionId/presentation': typeof AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute
  '/projects/$projectId/collections/$collectionId/entries/$entryId': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute
  '/projects/$projectId/collections/$collectionId/entries/$entryId/preview': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_auth/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/_auth/projects/$projectId_/operations': typeof AuthProjectsProjectIdOperationsRoute
  '/_auth/projects/$projectId_/webhooks': typeof AuthProjectsProjectIdWebhooksRoute
  '/_auth/projects/$projectId_/collections/$collectionId': typeof AuthProjectsProjectIdCollectionsCollectionIdRoute
  '/_auth/projects/$projectId_/collections/$collectionId_/entries': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute
  '/_auth/projects/$projectId_/collections/$collectionId_/presentation': typeof AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute
  '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute
  '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId_/preview': typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/login'
    | '/dashboard'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/projects/$projectId'
    | '/projects/$projectId/operations'
    | '/projects/$projectId/webhooks'
    | '/projects/$projectId/collections/$collectionId'
    | '/projects/$projectId/collections/$collectionId/entries'
    | '/projects/$projectId/collections/$collectionId/presentation'
    | '/projects/$projectId/collections/$collectionId/entries/$entryId'
    | '/projects/$projectId/collections/$collectionId/entries/$entryId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/login'
    | '/dashboard'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/projects/$projectId'
    | '/projects/$projectId/operations'
    | '/projects/$projectId/webhooks'
    | '/projects/$projectId/collections/$collectionId'
    | '/projects/$projectId/collections/$collectionId/entries'
    | '/projects/$projectId/collections/$collectionId/presentation'
    | '/projects/$projectId/collections/$collectionId/entries/$entryId'
    | '/projects/$projectId/collections/$collectionId/entries/$entryId/preview'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/device'
    | '/login'
    | '/_auth/dashboard'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/_auth/projects/$projectId'
    | '/_auth/projects/$projectId_/operations'
    | '/_auth/projects/$projectId_/webhooks'
    | '/_auth/projects/$projectId_/collections/$collectionId'
    | '/_auth/projects/$projectId_/collections/$collectionId_/entries'
    | '/_auth/projects/$projectId_/collections/$collectionId_/presentation'
    | '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId'
    | '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId_/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/projects/$projectId': {
      id: '/_auth/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId_/operations': {
      id: '/_auth/projects/$projectId_/operations'
      path: '/projects/$projectId/operations'
      fullPath: '/projects/$projectId/operations'
      preLoaderRoute: typeof AuthProjectsProjectIdOperationsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId_/webhooks': {
      id: '/_auth/projects/$projectId_/webhooks'
      path: '/projects/$projectId/webhooks'
      fullPath: '/projects/$projectId/webhooks'
      preLoaderRoute: typeof AuthProjectsProjectIdWebhooksRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId_/collections/$collectionId': {
      id: '/_auth/projects/$projectId_/collections/$collectionId'
      path: '/projects/$projectId/collections/$collectionId'
      fullPath: '/projects/$projectId/collections/$collectionId'
      preLoaderRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId_/collections/$collectionId_/entries': {
      id: '/_auth/projects/$projectId_/collections/$collectionId_/entries'
      path: '/projects/$projectId/collections/$collectionId/entries'
      fullPath: '/projects/$projectId/collections/$collectionId/entries'
      preLoaderRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId_/collections/$collectionId_/presentation': {
      id: '/_auth/projects/$projectId_/collections/$collectionId_/presentation'
      path: '/projects/$projectId/collections/$collectionId/presentation'
      fullPath: '/projects/$projectId/collections/$collectionId/presentation'
      preLoaderRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdPresentationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId': {
      id: '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId'
      path: '/projects/$projectId/collections/$collectionId/entries/$entryId'
      fullPath: '/projects/$projectId/collections/$collectionId/entries/$entryId'
      preLoaderRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId_/preview': {
      id: '/_auth/projects/$projectId_/collections/$collectionId_/entries_/$entryId_/preview'
      path: '/projects/$projectId/collections/$collectionId/entries/$entryId/preview'
      fullPath: '/projects/$projectId/collections/$collectionId/entries/$entryId/preview'
      preLoaderRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRoute
  AuthProjectsProjectIdOperationsRoute: typeof AuthProjectsProjectIdOperationsRoute
  AuthProjectsProjectIdWebhooksRoute: typeof AuthProjectsProjectIdWebhooksRoute
  AuthProjectsProjectIdCollectionsCollectionIdRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdRoute
  AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute
  AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute
  AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute
  AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute: typeof AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRoute,
  AuthProjectsProjectIdOperationsRoute: AuthProjectsProjectIdOperationsRoute,
  AuthProjectsProjectIdWebhooksRoute: AuthProjectsProjectIdWebhooksRoute,
  AuthProjectsProjectIdCollectionsCollectionIdRoute:
    AuthProjectsProjectIdCollectionsCollectionIdRoute,
  AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute:
    AuthProjectsProjectIdCollectionsCollectionIdEntriesRoute,
  AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute:
    AuthProjectsProjectIdCollectionsCollectionIdPresentationRoute,
  AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute:
    AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdRoute,
  AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute:
    AuthProjectsProjectIdCollectionsCollectionIdEntriesEntryIdPreviewRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router/index.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
